/*
  ============================================================
  FRASES / CÁPSULAS INSPIRADORAS
  ============================================================
  O Marco entrega uma frase impressa, sorteada, para cada
  cliente. Aqui elas viram uma experiência no site: o visitante
  "tira" uma mensagem e pode tirar outra.

  Estas são as frases reais do Marco (arquivo "150 frases cápsula").
  COMO EDITAR: cada frase fica entre aspas, separada por vírgula.
  Para adicionar, copie uma linha inteira e cole abaixo.
  ============================================================
*/

export const frases: string[] = [
  "O que você chama de “atraso” pode ser a vida te poupando de uma pressa que quebraria sua alma. Quando o tempo te segura, às vezes ele te protege.",
  "Não é falta de força: é excesso de peso invisível que você carregou por lealdade. Soltar não é abandonar; é devolver o que nunca foi seu.",
  "A mente pede certeza; a alma pede verdade. E a verdade quase sempre vem sem garantias.",
  "Você não precisa se consertar para merecer amor. Você precisa se lembrar de onde se perdeu de si.",
  "Há portas que só abrem quando você para de empurrar. E chaves que aparecem quando você finalmente escuta.",
  "O inconsciente não grita: ele repete. Toda repetição é um pedido de consciência.",
  "Cura não é “virar outra pessoa”. É voltar a habitar a própria vida sem medo de existir.",
  "A ansiedade é um futuro inventado com provas do passado. Respire: o agora é o único chão que não mente.",
  "Nem tudo que dói é ruim. Às vezes é a alma voltando a ter sensibilidade.",
  "O ego quer vencer; o Self quer integrar. A vitória real é quando você para de se partir por dentro.",
  "Você não está atrasado: está amadurecendo no ritmo do que é verdadeiro. O que é seu não precisa ser forçado.",
  "A gratidão não é negar a dor. É reconhecer que você ainda tem luz para atravessá-la.",
  "Quando você se julga demais, você se impede de aprender. Compaixão é a inteligência que abraça.",
  "A vida não te pune: ela te revela. Toda crise aponta onde você não estava inteiro.",
  "Silenciar o corpo é adiar a verdade. O corpo é o diário que a alma escreve sem palavras.",
  "Se a sua paz depende de alguém mudar, ela não é paz — é controle disfarçado. Paz é liberdade interna.",
  "Sua sombra não é inimiga; é potência sem educação. Iluminar não é expulsar — é orientar.",
  "Quem você “tem que ser” pode estar te impedindo de ser quem você é. Solte o personagem e respire como alma.",
  "A intuição é um saber sem barulho. Ela não compete com a mente; ela atravessa.",
  "Há um tipo de cansaço que é saudade de si. Descanse onde você se reencontra.",
  "A vida te testa onde você ainda negocia seu valor. O mundo cobra caro de quem não se honra.",
  "Você não precisa provar nada para existir. Existir já é um milagre competente.",
  "Cada “não” dito com verdade é um “sim” dado à sua dignidade. Limite é amor com coluna.",
  "Seu passado não é um cárcere; é um professor. Mas professor não é casa: aprenda e siga.",
  "O que te fere com frequência está mostrando um ponto cego. E todo ponto cego é convite para despertar.",
  "O perdão não absolve o erro; ele desata o nó dentro de você. Perdoar é soltar o veneno, não a lição.",
  "Você pode amar alguém e ainda assim escolher a si. Amor sem auto-respeito vira dívida emocional.",
  "O que você chama de “fraqueza” pode ser sensibilidade sem proteção. Fortaleça suas bordas, não mate sua essência.",
  "A mente cria histórias; o coração reconhece caminhos. Quando ambos se alinham, o mundo muda.",
  "Você não está “quebrado”; está em reorganização. A alma também faz reformas profundas.",
  "Às vezes, o problema não é a falta de energia. É o excesso de dispersão do seu foco.",
  "O que você resiste, persiste. O que você acolhe, se transforma.",
  "Você não precisa controlar o rio: precisa aprender a navegar. A vida não é contra você; ela é movimento.",
  "Se você está sempre se explicando, talvez esteja em lugares onde não te escutam. Presença não se mendiga.",
  "Há momentos em que o melhor passo é parar. Pausa também é direção.",
  "A solidão pode ser um deserto ou um templo. Depende se você foge de si ou se retorna.",
  "Você não precisa de mais respostas; precisa de mais verdade. A verdade acalma porque é simples.",
  "O medo não é sinal de incapacidade, é sinal de fronteira. Toda fronteira atravessada vira força.",
  "Nem toda saudade é de alguém. Às vezes é saudade de um “eu” que ficou para trás.",
  "O que é autêntico não grita. Ele sustenta, mesmo em silêncio.",
  "Seu coração sabe quando você está traindo sua verdade. Ele aperta para te acordar.",
  "Há uma sabedoria em não responder de imediato. Silêncio é maturidade em ação.",
  "Se você se perde para pertencer, você paga caro demais. Pertencimento real não exige mutilação.",
  "O que você chama de “caos” pode ser limpeza energética e emocional. A ordem nova nasce da bagunça antiga.",
  "A sombra aparece quando a luz interna cresce. Ela não veio te destruir; veio te integrar.",
  "Você não precisa vencer ninguém. Precisa vencer o hábito de se abandonar.",
  "A sua história tem capítulos duros, mas não é só isso. Você é o autor vivo: escreva com presença.",
  "O mundo responde diferente quando você se trata com respeito. Autoestima é postura invisível.",
  "Quem não tem limites vira morada de excessos alheios. Diga “não” para proteger o seu “sim”.",
  "Você não é suas emoções — você é o espaço que as percebe. E esse espaço é liberdade.",
  "A vida muda quando você muda a pergunta. “Por que eu?” vira “para que isso em mim?”",
  "A espiritualidade madura não foge da realidade. Ela a atravessa com consciência e amor.",
  "O seu valor não oscila com o humor dos outros. Valor é essência, não opinião.",
  "Não tenha vergonha de recomeçar. Vergonha é continuar onde sua alma definha.",
  "A mente busca segurança; a alma busca sentido. Quando você encontra sentido, a segurança cresce por dentro.",
  "Você não precisa carregar o mundo para ser amado. Amor real não pesa.",
  "O que você admira em alguém é uma pista do que vive em você. Admiração é espelho do potencial.",
  "Não se culpe por sentir. Sentir é o modo como a vida te mantém humano.",
  "A comparação é o roubo silencioso da sua paz. Seu caminho não precisa parecer com nenhum outro.",
  "O que você chama de “limite” pode ser o início da sua liberdade. Fronteira bem colocada vira calma.",
  "Há um tipo de tristeza que é luto por um sonho antigo. Honre o sonho e escolha o próximo passo.",
  "Você não precisa estar “100%” para começar. Comece com o que você tem: o caminho te fortalece.",
  "Nem toda perda é castigo. Algumas são libertação disfarçada.",
  "O inconsciente fala em símbolos; a vida também. Preste atenção no que se repete como sinal.",
  "A cura não acontece só na mente. Ela desce para o corpo quando você se sente seguro.",
  "Você não deve nada ao passado além de aprendizado. O futuro te pede presença.",
  "Há pessoas que te amam pelo papel que você cumpre. E há pessoas que te amam pelo que você é.",
  "O que é verdadeiro em você não precisa de aprovação. Precisa de compromisso.",
  "A raiva, quando consciente, vira direção. Quando negada, vira veneno.",
  "Um “sim” dito por medo vira prisão. Um “não” dito por amor vira paz.",
  "Quem você é em silêncio revela quem você é de verdade. Cultive um lugar interno que não negocia.",
  "O medo de errar te impede de viver. Errar é laboratório da alma.",
  "Quando você escolhe a si, o mundo se reorganiza. A vida respeita quem se honra.",
  "Você não precisa se endurecer para sobreviver. Precisa se fortalecer sem perder ternura.",
  "Há decisões que parecem egoístas, mas são auto-cuidado tardio. Você também é alguém que você ama.",
  "O corpo relaxa quando a alma confia. A confiança nasce da verdade, não da promessa.",
  "A vida te dá sinais antes de te dar sacudidas. Se escute no sussurro para não aprender no grito.",
  "Você não atrai o que “quer”, você atrai o que sustenta. Sustente dentro o que deseja fora.",
  "Seus padrões são tentativas antigas de proteção. A maturidade é atualizar a proteção.",
  "Cada vez que você respira com presença, você volta para casa. Casa é o agora.",
  "O que você chama de “azar” pode ser alinhamento te afastando do errado. Nem toda porta fechada é perda.",
  "A paz não é ausência de problemas. É presença de centro.",
  "O silêncio é um espelho: ele mostra o que você tenta abafar. Sente, respira, escuta.",
  "Você não precisa se punir para evoluir. Evolução é consciência, não chicote.",
  "Quando você acolhe sua história, ela para de te assombrar. Aceitar é transformar memória em sabedoria.",
  "Quem você se torna importa mais do que o que você conquista. Conquista sem alma vira vazio.",
  "Não confunda intensidade com verdade. O que é verdadeiro permanece, mesmo calmo.",
  "A vida te convida a sair do automático e entrar no autoral. Autoral é viver com escolha.",
  "Sua energia segue sua atenção. Cuide onde você mora por dentro.",
  "O amor que você procura fora começa no modo como você se trata. Autoamor é o primeiro relacionamento.",
  "Quando você honra sua intuição, você economiza dor. Intuição é atalho com responsabilidade.",
  "Não romantize a exaustão. Exaustão é um pedido de mudança.",
  "Seu caminho não precisa ser entendido por todos. Precisa ser sustentado por você.",
  "Às vezes, você chama de “confusão” o que é só verdade chegando. A verdade desmonta ilusões.",
  "A ansiedade diminui quando você para de viver em dívida com o futuro. Faça hoje o que é possível, com presença.",
  "Você não é frágil por sentir profundamente. Você é vivo — e isso é força.",
  "A vida te dá lições até você aprender o que insiste em ignorar. Aprender é suavizar o destino.",
  "O perdão a si mesmo é o começo de toda reprogramação real. Sem isso, o progresso vira máscara.",
  "O que você chama de “destino” pode ser escolha repetida. Mude a escolha, muda o caminho.",
  "Há uma parte sua que sabe exatamente o que fazer. Ela só precisa de silêncio para falar.",
  "Você não precisa de mais controle; precisa de mais confiança. Confiança é fé aplicada no cotidiano.",
  "Seu corpo é um altar: trate-o com reverência. Saúde é espiritualidade na matéria.",
  "Quando você se respeita, você para de aceitar migalhas. E migalhas nunca alimentaram alma nenhuma.",
  "A vida é generosa com quem tem coragem de ser verdadeiro. Verdade atrai caminhos limpos.",
  "Você não precisa curar tudo de uma vez. Precisa apenas dar hoje um passo honesto.",
  "A sua sombra guarda dons que você rejeitou por medo. Integre: ali mora potência.",
  "Se você quer paz, pare de discutir com a realidade. Aceite o que é, e transforme o que pode.",
  "A mente é excelente serva, péssima senhora. Quem lidera sua vida é a sua consciência.",
  "Quando você diz “eu não consigo”, pergunte: “o que eu ainda não aprendi?” Essa pergunta abre portas internas.",
  "Nem toda saudade merece retorno. Às vezes, é só o hábito chamando.",
  "Sua energia não é infinita: direcione. Escolher é cuidar.",
  "O que te dá vergonha pode ser o lugar onde sua alma quer liberdade. Vergonha é medo de ser visto.",
  "Quando você se alinha, a vida coopera. O universo gosta de coerência.",
  "Cuidado com o vício de sobreviver. Você veio para viver.",
  "Quando você se perdoa, você para de se punir com escolhas repetidas. Autoperdão é renascimento.",
  "Sua sensibilidade é um dom que precisa de limites. Sem limites, dom vira ferida.",
  "Você não precisa explicar seu processo para quem só entende resultado. Crescimento é invisível até florescer.",
  "A vida não exige perfeição; exige honestidade. Honestidade cura mais do que performance.",
  "O que te prende muitas vezes é um “talvez” alimentado por medo. Escolha: clareza é libertação.",
  "O futuro não se controla, se prepara. Preparar é alinhar mente, corpo e coração.",
  "Toda vez que você escolhe a verdade, você se aproxima do seu destino. Mentiras atrasam, mesmo que aliviem.",
  "O amor próprio não é egoísmo. É o alicerce para amar sem se abandonar.",
  "O que cura não é só entender — é sentir com segurança. E segurança nasce quando você se acolhe.",
  "Você não precisa ter tudo resolvido para ser digno. Você só precisa ser honesto com seu processo.",
  "Que hoje você se trate como trataria alguém que ama profundamente. Esse é o gesto que muda vidas — por dentro, e para sempre.",
  "A pressa é uma forma de violência interna. A alma não floresce sob ameaça.",
  "A coragem não é ausência de medo. É presença apesar do medo.",
  "Você não está “sendo difícil”. Você está amadurecendo e isso muda suas tolerâncias.",
  "Se um padrão se repete, ele quer ser visto. Consciência é a luz que desarma o ciclo.",
  "Às vezes, a vida não quer que você “consiga”. Ela quer que você se torne.",
  "Você não precisa de permissão para se reconstruir. O recomeço é um direito da consciência.",
  "A culpa é uma tentativa de pagar com dor o que se resolve com mudança. Aprenda e faça diferente: isso é redenção.",
  "Você não é obrigado a manter vínculos que te adoecem. Amor sem saúde vira dependência.",
  "Quando você muda por dentro, algumas pessoas estranham. Elas estavam acostumadas com sua ausência.",
  "A espiritualidade real é prática: cuidado, presença, coerência. O resto é enfeite.",
  "A sua vida pede menos “provar” e mais “viver”. Viver é a oração mais concreta.",
  "Se você não se respeita, você ensina o mundo a não te respeitar. Respeito começa em casa.",
  "Há uma beleza profunda em ser iniciante de novo. Humildade abre portas que o orgulho fecha.",
  "Quando você honra seu corpo, sua mente suaviza. O corpo é a casa onde a consciência mora.",
  "A dor que você evita vira padrão. A dor que você encara vira caminho de cura.",
  "Você não precisa “merecer descanso”. Descanso é uma necessidade sagrada.",
  "A vida te tira o que você usa para fugir do essencial. E chama isso de “crise”, para você prestar atenção.",
  "Sua mente lembra, mas seu corpo guarda. Por isso, curar é também devolver segurança ao corpo.",
  "A felicidade madura não é euforia. É serenidade que não depende do externo.",
  "Você não é um problema a ser resolvido. Você é um mistério a ser vivido com amor.",
  "A vida te pede presença, não perfeição. Presença transforma o comum em sagrado.",
  "O caminho do despertar começa quando você para de fugir de si. E decide se encontrar, com coragem e ternura.",
  "Não espere “um dia melhor” para ser gentil consigo. Gentileza interna cria dias melhores.",
  "Quando você honra seus limites, você protege sua luz. E luz protegida ilumina mais.",
  "Todo padrão que te prende um dia te protegeu. Agradeça — e atualize.",
  "Você não precisa vencer o passado; precisa aprender com ele. O passado vira bênção quando vira consciência.",
  "A vida não te pede pressa; te pede verdade. A verdade é o ritmo do que permanece.",
  "Se você quer mudança externa, comece pela conversa interna. As palavras que você usa viram o mundo que você vive.",
  "Você não está sozinho: há uma inteligência maior te guiando por dentro. Silencie e perceba o próximo passo.",
  "Respire: o agora é mais seguro do que a sua imaginação diz. E a sua alma sabe caminhar.",
  "O Caminho do Despertar é simples e exigente: presença, verdade, coragem. Todo o resto se reorganiza quando você se escolhe.",
  "A cada mensagem que você recebe, pergunte: “o que isso quer acordar em mim?” Quando você faz essa pergunta, você já começou a mudar.",
];
